SCLN-63 Internal Printing Enhancements
AssemblyPayments/spi-client-ios pull request #33
Opened 2019-01-29 06:43 UTC by metinavci

2019-01-30 06:01 UTC, chrishulbert approved these changes

2019-02-04 04:38 UTC, chrishulbert requested changes
Looks pretty good!

2019-02-04 04:38 UTC, chrishulbert commented on Library/Model/SPIPayAtTable.h
> +@property (nonatomic, retain) NSString *tableId;
```suggestion
@property (nonatomic, copy) NSString *tableId;
```

2019-02-04 04:38 UTC, chrishulbert commented on Library/Model/SPIPayAtTable.h
> +@property (nonatomic, retain) NSString *label;
```suggestion
@property (nonatomic, copy) NSString *label;
```

2019-02-04 04:38 UTC, chrishulbert commented on Library/Model/SPIPayAtTable.h
> +@property (nonatomic, retain) NSString *tableData;
```suggestion
@property (nonatomic, copy) NSString *tableData;
```

2019-02-04 04:38 UTC, chrishulbert commented on Library/Model/SPIPayAtTable.h
> +@property (nonatomic, retain) NSString *billId;
```suggestion
@property (nonatomic, copy) NSString *billId;
```

2019-02-04 04:38 UTC, chrishulbert commented on Library/Model/SPITransaction.m
> +    [data setValue:@(_purchaseAmount) forKey:@"purchase_amount"];
neat!

2019-02-04 05:41 UTC, metinavci commented on Library/Model/SPIPayAtTable.h
> +@property (nonatomic, retain) NSString *tableId;
done

2019-02-04 05:41 UTC, metinavci commented on Library/Model/SPIPayAtTable.h
> +@property (nonatomic, retain) NSString *label;
done

2019-02-04 05:41 UTC, metinavci commented on Library/Model/SPIPayAtTable.h
> +@property (nonatomic, retain) NSString *tableData;
done

2019-02-04 05:42 UTC, metinavci commented on Library/Model/SPIPayAtTable.h
> +@property (nonatomic, retain) NSString *billId;
done

2019-02-04 05:44 UTC, chrishulbert approved these changes

2019-02-04 22:18 UTC, chrishulbert approved these changes
I think i reviewed all this already in another PR

2019-02-19 05:17 UTC, chrishulbert approved these changes

2019-03-04 00:24 UTC, merged